DAPPBUILDER/dApp-Builder

- dApp Builder smart contracts/voting.sol
> Voting smart contract

- dApp Builder site/assets/js/constructor/voting.js
> Votin dApp creation JS interface added

- dApp Builder site/classes/.htaccess
- dApp Builder site/classes/Dapp.php
- dApp Builder site/classes/Helper.php
- dApp Builder site/classes/User.php
- dApp Builder site/common/.htaccess
- dApp Builder site/common/footer.php
- dApp Builder site/common/header.php
- dApp Builder site/create_dapp.php
- dApp Builder site/deploy_dapp.php
- dApp Builder site/new-dapp.php
> Voting dApp constructor added

- dApp Builder site/dapps/.htaccess
- dApp Builder site/dapps/voting.php
- dApp Builder site/my-dapps.php
> Voting Dapp UI for end users added

- dApp Builder site/change_template.php
- dApp Builder site/classes/Dapp.php
- dApp Builder site/dapps/voting.php
- dApp Builder site/my-dapps.php
> Voting dApp UI customization

- dApp Builder site/dapp.php
- dApp Builder site/dapps/voting.php
> Voting dApp fix

- dApp Widget/Android/src/main/assets/ethereum_content.html
- dApp Widget/Android/src/main/java/com/ibuildapp/romanblack/WebPlugin/WebPlugin.java
> Udate widget

- dApp Builder smart contracts/ibaEscrow.sol
> added escrow source

- dApp Builder smart contracts/dapEscrow.sol
> renamed escrow and solver security issue with refund method

- dApp Builder site/new-dapp.php
> MetaMask problems fixed

- dApp Builder site/dapp.php
- dApp Builder site/dapps/escrow.php
> Escrow dApp UI for end users added

- dApp Builder site/my-dapps.php
> Escrow dApp UI customization added

- dApp Builder site/assets/js/constructor/escrow.js
> dApp creation js added

- dApp Builder site/assets/js/constructor/escrow.js
- dApp Builder site/assets/js/constructor/multisig.js
- dApp Builder site/assets/js/constructor/voting.js
> multisig contract creation UI added

- dApp Builder site/assets/css/profile.css
- dApp Builder site/create_dapp.php
- dApp Builder site/deploy_dapp.php
- dApp Builder site/new-dapp.php
> multisig creation form added

- dApp Builder site/classes/Dapp.php
- dApp Builder site/dapp.php
- dApp Builder site/dapps/escrow.php
- dApp Builder site/dapps/voting.php
> multisig ui added

- dApp Builder site/dapps/multisig.php
- dApp Builder site/my-dapps.php
> multisig UI customization added

- dApp Builder smart contracts/dapBetting.sol
> Betting smart contract

- dApp Builder site/assets/js/constructor/betting.js
- dApp Builder site/assets/js/constructor/escrow.js
- dApp Builder site/assets/js/constructor/voting.js
> betting UI js added

- dApp Builder site/common/profiledata.php
- dApp Builder site/create_dapp.php
- dApp Builder site/deploy_dapp.php
- dApp Builder site/new-dapp.php
> betting dapp creation form added

- dApp Builder site/classes/Dapp.php
- dApp Builder site/classes/User.php
- dApp Builder site/my-dapps.php
> betting dapp UI customization added

- dApp Builder site/common/dapp-placeholder.php
- dApp Builder site/dapps/betting.php
- dApp Builder site/dapps/escrow.php
- dApp Builder site/dapps/multisig.php
- dApp Builder site/dapps/voting.php
> betting: UI for end users added

- dApp Builder smart contracts/iToken.sol
> added contract

- dApp Builder smart contracts/dapBetting.sol
betting contract updates: block&value limits
> added parameters
